/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/A0HSZcxxocM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Caudex } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"
import React from 'react'
import Image from 'next/image'

const Bloginfo = () => {
  return (
    <>
      {/* <header className="bg-gray-900 text-white py-4 px-6 md:px-8 lg:px-10">
        <div className="container mx-auto flex items-center justify-between">
          <Link className="flex items-center" href="#">
            <FlagIcon className="h-8 w-8 mr-2" />
            <span className="text-xl font-bold">Blog Website</span>
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:underline" href="#">
              Home
            </Link>
            <Link className="hover:underline" href="#">
              Blog
            </Link>
            <Link className="hover:underline" href="#">
              About
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <div className="relative">
              <Input
                className="bg-gray-800 border-none focus:ring-2 focus:ring-gray-600 focus:outline-none px-4 py-2 rounded-md text-sm"
                placeholder="Search..."
                type="text"
              />
              <SearchIcon className="absolute right-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
            </div>
            <Button variant="primary">Subscribe</Button>
          </div>
        </div>
      </header> */}
      <main>
        {/* <section className="bg-gray-900 text-white py-20 md:py-32 lg:py-40">
          <div className="container mx-auto flex flex-col md:flex-row items-center justify-between">
            <div className="md:w-1/2 space-y-6">
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold">Welcome to our Blog</h1>
              <p className="text-lg md:text-xl">Discover the latest news, insights, and stories from our team.</p>
              <Button>Read More</Button>
            </div>
            <Image
              alt="Hero Image"
              className="md:w-1/2 aspect-[4/2] object-cover rounded-lg mt-8 md:mt-0"
              height={400}
              src="./placeholder.svg"
              width={800}
            />
          </div>
        </section> */}
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto">
            <h2 className="text-center text-3xl md:text-4xl lg:text-5xl font-bold mb-8">Latest Blog Posts</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
              <Card>
                <Image
                  alt="Blog Post Image"
                  className="rounded-t-lg object-cover"
                  height={250}
                  src="./placeholder.svg"
                  style={{
                    aspectRatio: "400/250",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Blog Post Title</h3>
                  <p className="text-gray-500 mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  <Link className="text-blue-500 hover:underline" href="#">
                    Read More
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <Image
                  alt="Blog Post Image"
                  className="rounded-t-lg object-cover"
                  height={250}
                  src="./placeholder.svg"
                  style={{
                    aspectRatio: "400/250",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">Another Blog Post</h3>
                  <p className="text-gray-500 mb-4">
                    Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  </p>
                  <Link className="text-blue-500 hover:underline" href="#">
                    Read More
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <Image
                  alt="Blog Post Image"
                  className="rounded-t-lg object-cover"
                  height={250}
                  src="./placeholder.svg"
                  style={{
                    aspectRatio: "400/250",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent>
                  <h3 className="text-xl font-bold mb-2">A Third Blog Post</h3>
                  <p className="text-gray-500 mb-4">
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.
                  </p>
                  <Link className="text-blue-500 hover:underline" href="#">
                    Read More
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      {/* <footer className="bg-gray-900 text-white py-8 px-6 md:px-8 lg:px-10">
        <div className="container mx-auto flex flex-col md:flex-row items-center justify-between">
          <div className="flex items-center">
            <FlagIcon className="h-8 w-8 mr-2" />
            <span className="text-xl font-bold">Blog Website</span>
          </div>
          <nav className="flex items-center space-x-6 mt-4 md:mt-0">
            <Link className="hover:underline" href="#">
              Home
            </Link>
            <Link className="hover:underline" href="#">
              Blog
            </Link>
            <Link className="hover:underline" href="#">
              About
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </nav>
        </div>
      </footer> */}
    </>
  )
}

export default Bloginfo


// function FlagIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
//       <line x1="4" x2="4" y1="22" y2="15" />
//     </svg>
//   )
// }


// function SearchIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="11" cy="11" r="8" />
//       <path d="m21 21-4.3-4.3" />
//     </svg>
//   )
// }
