/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/czaE3WPWhHL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Image from 'next/image'

import React from 'react'

const DescribedSection = () => {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
    <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
      <Image
        alt="Book Cover"
        className="mx-auto overflow-hidden rounded-xl object-cover sm:w-full"
        height={300}
        src="./placeholder.svg"
        width={550}
      />
      <div className="space-y-4">
        <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">The Alchemist</h1>
        <p className="text-lg text-gray-500 dark:text-gray-400">By Paulo Coelho</p>
        <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
          The Alchemist is a novel by Brazilian author Paulo Coelho that was first published in 1988. The story
          follows a young shepherd in Spain who dreams of traveling the world in search of a treasure as fabulous as
          any ever found.
        </p>
        <Button size="lg">Know More</Button>
      </div>
    </div>
  </section>
  )
}

export default DescribedSection

