/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mUZEVnN6ZPJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import React from 'react'

const footer = () => {
  return (
    <footer className="bg-black p-6 md:py-12 w-full dark:bg-black-800">
      <div className="container max-w-7xl flex flex-col items-center gap-6 sm:flex-row sm:justify-between">
        <div className="flex items-center gap-2">
        <svg className="h-6 w-6"
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
          {/* <MountainIcon className="h-6 w-6" /> */}
          <span className="text-sm font-medium">Acme Inc</span>
        </div>
        <nav className="flex flex-wrap items-center gap-4 text-sm">
          <Link className="text-white hover:underline" href="/">
            Home
          </Link>
          <Link className="text-white hover:underline" href="/About">
            About
          </Link>
          <Link className="text-white hover:underline" href="/Service">
            Service
          </Link>
          <Link className="text-white hover:underline" href="/Contact">
            Contact
          </Link>
        </nav>
        <p className="text-white text-sm dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
      </div>
    </footer>
  )
}

export default footer


// function MountainIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
//     </svg>
//   )
// }
