/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/o5l4jS2W65Q
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

import React from 'react'

const HeaderSection = () => {
  return (
    <section className="relative w-full h-[500px] bg-[url(/placeholder.svg)] bg-cover bg-center">
      <div className="absolute inset-0 bg-gray-900/50 flex flex-col items-center justify-center text-center px-4 md:px-6">
        <h1 className="text-3xl font-bold text-white sm:text-4xl md:text-5xl lg:text-6xl">Unleash Your Creativity</h1>
        <p className="mt-4 text-gray-300 max-w-[700px] text-lg md:text-xl">
          Discover a world of endless possibilities and let your imagination soar. Explore our collection of inspiring
          resources and unlock your true potential.
        </p>
        <Link
          className="mt-8 inline-flex items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2"
          href="#"
        >
          Read More
        </Link>
      </div>
    </section>
  )
}

export default HeaderSection