/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Rfgstdj7tZm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import About from '@/app/About/page'

import React from 'react'

const HeadNavBar = () => {
  return (
    <header className="flex items-center justify-between bg-white px-6 py-4 shadow-sm dark:bg-gray-950">
      <Link className="flex items-center gap-2" href="/">
      <svg className="h-5 w-5"
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>
        <span className="text-lg font-semibold">PhotoStudioDesign</span>
      </Link>
      <nav className="hidden md:flex items-center gap-6">
        <Link
          className="text-sm font-medium transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
          href="/"
        >
          Home
        </Link>
        <Link
          className="text-sm font-medium transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
          href="/About"
        >
          About
        </Link>
        <Link
          className="text-sm font-medium transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
          href="/Service"
        >
          Service
        </Link>
        <Link
          className="text-sm font-medium transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
          href="/Contact"
        >
          Contact
        </Link>
      </nav>
      <div className="flex items-center gap-4">
        <Link
          className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
          href="/login"
        >
          Login
        </Link>
      </div>
    </header>
  )
}

export default HeadNavBar






