/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PnqDIBC0fgU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { Checkbox } from "../ui/checkbox"
import Link from "next/link"
import { Button } from "../ui/button"
import { CardContent, Card } from "@/components/ui/card"
import React from 'react'

const Login = () => {
  return (
    <div className="flex items-center justify-center h-screen">
    <Card>
    <CardContent>
    <div className = "container mx-auto sm:w-500 mt-8">
      {/* <div className="box-border sm-content"> */}
        <div className="text-center">
          <h2 className="pb-8 text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Sign in to your account</h2>
        </div>
        <form action="#" className="space-y-6" method="POST">
          <div>
            <Label className=" block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="email">
              Email address
            </Label>
            <div className="mt-1">
              <Input
                autoComplete="email"
                className="block sm:w-200 appearance-none rounded-md border border-gray-200 border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-50 dark:placeholder-gray-400 dark:border-gray-800"
                id="email"
                name="email"
                required
                type="email"
              />
            </div>
          </div>
          <div>
            <Label className="block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="password">
              Password
            </Label>
            <div className="mt-1">
              <Input
                autoComplete="current-password"
                className="block w-full appearance-none rounded-md border border-gray-200 border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-50 dark:placeholder-gray-400 dark:border-gray-800"
                id="password"
                name="password"
                required
                type="password"
              />
            </div>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Checkbox
                className="h-4 w-4 rounded text-indigo-600 focus:ring-indigo-500 dark:bg-gray-800 dark:ring-offset-gray-800 dark:focus:ring-indigo-600"
                id="remember-me"
                name="remember-me"
              />
              <Label className="ml-2 block text-sm text-gray-900 dark:text-gray-300" htmlFor="remember-me">
                Remember me
              </Label>
            </div>
            <div className="text-sm">
              <Link
                className="font-medium text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
                href="#"
              >
                Forgot your password?
              </Link>
            </div>
          </div>
          <div className="flex justify-center">
            <Button
              className="flex pr-8 pl-8 justify-center rounded-md border border-gray-200 border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:bg-indigo-500 dark:hover:bg-indigo-600 dark:focus:ring-indigo-600 dark:focus:ring-offset-gray-950 dark:border-gray-800"
              type="submit"
            >
              Sign in
            </Button>
          </div> 
        </form>
      {/* </div> */}
    </div>
    </CardContent>
    </Card>
    </div>
    
  )
}

export default Login